__author__ = "Marius Kirchner, Goethe University Frankfurt am Main"

from PetriNetObject import PetriNet

#default

#init Petri
MainPetri = PetriNet()

#put places
MainPetri.addPlace(0, "PlaceZero", 10, [], [])
MainPetri.addPlace(1, "PlaceOne", 10, [], [])
MainPetri.addPlace(2, "PlaceTwo", 10, [], [])
MainPetri.addPlace(3, "PlaceThree", 10, [], [])
MainPetri.addPlace(4, "PlaceFour", 10, [], [])

#put transitions
MainPetri.addTransition(0, "TransitionZero", [0], [1, 2])
MainPetri.addTransition(1, "TransitionOne", [1], [])
MainPetri.addTransition(2, "TransitionTwo", [], [3])
MainPetri.addTransition(3, "TransitionThree", [2, (3, 2)], [4])
MainPetri.addTransition(4, "TransitionFour", [4], [])
MainPetri.addTransition(5, "TransitionFive", [4], [(0, 2)])

MainPetri.printPlaces()
MainPetri.printTransitions()
MainPetri.printEdges()

MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()
MainPetri.simulateStep()

MainPetri.printPlaces()

SecondPetri = PetriNet()
SecondPetri.addPlace(0, "Env_Nutrient", 10, [], [])
SecondPetri.addPlace(1, "Move_Inhibited", 0, [], [])
SecondPetri.addPlace(2, "Move_Activated", 1, [], [])
SecondPetri.addPlace(3, "Nutrient", 10, [], [])
SecondPetri.addPlace(4, "Beh_Move", 0, [], [])
SecondPetri.addPlace(5, "Beh_Size", 0, [], [])
SecondPetri.addPlace(6, "Beh_Replication", 0, [], [])

SecondPetri.addTransition(0, "Intake_Nutrition", [0], [(3, 5)])
SecondPetri.addTransition(1, "ActiveInhibition_1", [0, 2], [0, 1], 1)
SecondPetri.addTransition(2, "PassiveUninhibition_0", [1], [2], 0)
SecondPetri.addTransition(3, "Nutrient_to_Move", [2, 3], [2, 4])
SecondPetri.addTransition(4, "Nutrient_to_Size", [(3, 12)], [5])
SecondPetri.addTransition(5, "Size_to_Replication", [(5, 10)], [6])


SecondPetri.printPlaces()
SecondPetri.printTransitions()
SecondPetri.printEdges()

SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")
SecondPetri.simulateStep()
SecondPetri.printPlaces()
print("=")